using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkylightEmulator.Communication.Headers
{
    public class r26Outgoing
    {
        public static readonly uint Connected = 0;
        public static readonly uint SecretKey = 2002;
        public static readonly uint UnknownHandshake = 277;
        public static readonly uint SomeKeysMaybe = 257;
        public static readonly uint Fuserights = 2;
        public static readonly uint SendClubMembership = 7;
        public static readonly uint SendUserInfo = 5;
        public static readonly uint SendTicketsInfo = 124;
        public static readonly uint SendRooms = 220;
        public static readonly uint SendNotifFromAdmin = 139;
        public static readonly uint AuthenicationOK = 3;
        public static readonly uint RoomForward = 286;
        public static readonly uint UpdateCredits = 6;
        public static readonly uint Badges = 229;
        public static readonly uint GuestRoomInfo = 54;
        public static readonly uint Advertisement = 258;
        public static readonly uint EnterPrivateRoom = 19;
        public static readonly uint EnterCheckRoom = 41;
        public static readonly uint LoadingRoomInfo = 69;
        public static readonly uint ApplyRoomEffect = 46;
        public static readonly uint IsRoomOwner = 47;
        public static readonly uint GiveRoomRights = 42;
        public static readonly uint RoomRating = 345;
        public static readonly uint Heightmap = 31;
        public static readonly uint SetRoomUser = 28;
        public static readonly uint FloorItems = 32;
        public static readonly uint GroupBadges = 309;
        public static readonly uint SendFurniAliases = 297;
        public static readonly uint WallItems = 45;
        public static readonly uint SpriteIndex = 295;
        public static readonly uint RoomAdvertisement = 208;
        public static readonly uint Unknown = 166;
        public static readonly uint PublicItems = 30;
        public static readonly uint UserStatues = 34;
        public static readonly uint MessengerFriends = 12;
        public static readonly uint FriendRequests = 314;
        public static readonly uint TypingStatus = 361;
        public static readonly uint Say = 24;
        public static readonly uint Shout = 26;
        public static readonly uint GetRandomRooms = 351;
        public static readonly uint MessengerSearchResult = 435;
        public static readonly uint MeesengerUpdate = 13;
        public static readonly uint Pong = 50;
        public static readonly uint UserLeaveRoom = 29;
        public static readonly uint LeaveRoom = 18;
        public static readonly uint FlatCats = 221;
        public static readonly uint Events = 368;
        public static readonly uint Recycle = 303;
        public static readonly uint RecycleSession = 304;
        public static readonly uint Swimsuit = 96;
        public static readonly uint SpecialCast = 71;
        public static readonly uint StartWobbleCountdown = 115;
        public static readonly uint StartWobbleGame = 114;
        public static readonly uint WobbleUpdate = 118;
        public static readonly uint WobbleEnd = 116;
        public static readonly uint WonWobble = 119;
        public static readonly uint WobbleFell = 72;
        public static readonly uint CreatedRoom = 59;
        public static readonly uint NoOwnRooms = 57;
        public static readonly uint Ownrooms = 16;
        public static readonly uint CatalogIndexes = 126;
        public static readonly uint CatalogPage = 127;
        public static readonly uint CurrenttHand = 140;
        public static readonly uint RoomSearchNoResults = 58;
        public static readonly uint RoomSearchResults = 55;
        public static readonly uint WobbleTie = 120;
        public static readonly uint WobbleTimeout = 117;
        public static readonly uint OpenGameBoard = 145;
        public static readonly uint GameBoardData = 144;
        public static readonly uint CameraFilm = 4;
        public static readonly uint OpenStickyOrPhoto = 48;
        public static readonly uint MachineID = 439;
        public static readonly uint SendSessionParamenters = 257;
        public static readonly uint PlaceFloorItem = 93;
        public static readonly uint AddWallItemToRoom = 83;
        public static readonly uint MoveFloorItem = 95;
        public static readonly uint RemoveFloorItem = 94;
        public static readonly uint RemoveWallItem = 84;
        public static readonly uint UpdateItem = 88;
        public static readonly uint PrivateChat = 134;
        public static readonly uint MessengerChatError = 261;
        public static readonly uint NewFriendRequest = 132;
    }
}
