using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkylightEmulator.Communication.Headers
{
    public class r63bOutgoing
    {
        public static readonly uint SendNotifFromMod = 3192;
        public static readonly uint AuthenicationOK = 1065;
        public static readonly uint Fuserights = 978;
        public static readonly uint AvaiblityStatus = 1060;
        public static readonly uint Logging = 2017;
        public static readonly uint HomeRoom = 1994;
        public static readonly uint FavouriteRooms = 2429;
        public static readonly uint SendUserInfo = 2228;
        public static readonly uint UpdateCredits = 2995;
        public static readonly uint UpdateActivityPoints = 2719;
        public static readonly uint UpdateActivityPointsSilence = 2542;
        public static readonly uint SendClubMembership = 2974;
        public static readonly uint SoundSettings = 1935;
        public static readonly uint MessengerFriends = 398;
        public static readonly uint FriendRequests = 314;
        public static readonly uint MeesengerUpdate = 1141;
        public static readonly uint FlatCats = 221;
        public static readonly uint BadgePoints = 1614;
        public static readonly uint EnterPrivateRoom = 3798;
        public static readonly uint LoadingRoomInfo = 999;
        public static readonly uint Heightmap = 9;
        public static readonly uint RelativeHeightmap = 2483;
        public static readonly uint PublicItems = 3713;
        public static readonly uint RoomOwner = 1084;
        public static readonly uint RoomData = 3116;
        public static readonly uint SetRoomUser = 2204;
        public static readonly uint UserStatues = 493;
        public static readonly uint LeaveRoom = 567;
        public static readonly uint UserLeavedRoom = 3770;
        public static readonly uint FloorItems = 3580;
        public static readonly uint WallItems = 3096;
        public static readonly uint NewItemAdded = 1642;
        public static readonly uint RoomVIPSettings = 939;
        public static readonly uint GiveRoomRights = 1496;
        public static readonly uint IsRoomOwner = 213;
        public static readonly uint UpdateRoomFloorItem = 2565;
        public static readonly uint DoorBellNoAnswer = 3941;
        public static readonly uint RoomError = 2120;
        public static readonly uint Doorbell = 265;
        public static readonly uint RoomErrorOnEnter = 2945;
        public static readonly uint SendNotifFromAdmin = 2491;
        public static readonly uint MOTD = 2307;
        public static readonly uint Dance = 3301;
        public static readonly uint AddBadges = 3148;
        public static readonly uint SetActiveBadges = 178;
        public static readonly uint TypingStatus = 851;
        public static readonly uint ModTool = 2659;
        public static readonly uint UserTags = 2884;
        public static readonly uint ApplyRoomEffect = 3663;
        public static readonly uint Handitem = 1773;
        public static readonly uint Effect = 329;
        public static readonly uint AchievementUnlocked = 1173;
        public static readonly uint AchievementUpdate = 1888;
        public static readonly uint Crypto = 3500;
        public static readonly uint SecretKey = 659;
        public static readonly uint MachineID = 1130;
        public static readonly uint BadgePointLimits = 1225;
        public static readonly uint Flood = 1641;
        public static readonly uint Sleeps = 746;
        public static readonly uint RoomRating = 3401;
        public static readonly uint IgnoredList = 3274;
        public static readonly uint Prizes = 894;
        public static readonly uint CampaingData = 1064;
        public static readonly uint AchievementCompetion = 827;
        public static readonly uint CommunityGoal = 3869;
        public static readonly uint Games = 2079;
        public static readonly uint GameAchievements = 1516;
        public static readonly uint AccountGameStatus = 1414;
        public static readonly uint UserPerks = 519;
        public static readonly uint Talk = 2119;
        public static readonly uint Shout = 3165;
        public static readonly uint Navigator = 2160;
        public static readonly uint PublicRooms = 3700;
        public static readonly uint Action = 523;
        public static readonly uint UnlockedAchievement = 1173;
        public static readonly uint CanCreateRoom = 3859;
        public static readonly uint FlatRoomCreated = 290;
        public static readonly uint InventoryItems = 177;
        public static readonly uint AddFloorItemToRoom = 1243;
        public static readonly uint RemoveItemFromHand = 606;
        public static readonly uint RemoveFloorItem = 2113;
        public static readonly uint AddItemToHand = 1102;
        public static readonly uint RemoveWallItem = 2208;
        public static readonly uint CatalogIndex = 2563;
        public static readonly uint CatalogPage = 2826;
        public static readonly uint BuyInfo = 1128;
        public static readonly uint RollerMovement = 1508;
        public static readonly uint LoadGame = 2969;
        public static readonly uint GameButtonStatus = 460;
        public static readonly uint LeaveGameQueue = 2025;
        public static readonly uint GiveRespect = 2283;
        public static readonly uint RoomSettingsOK = 1926;
        public static readonly uint RoomUpdatedOK = 3530;
        public static readonly uint StartTrade = 2567;
    }
}
